# fly.toml app configuration file generated for mediaflowforibuu on 2025-03-23T20:59:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mediaflowforibuu'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 512
